#incident_data/display_names.py

incident_display_names = {
    "cardiac_arrest": "Cardiac Arrest / Heart Attack",
    "stroke": "Stroke",
    "breathing_difficulty": "Difficulty Breathing",
    "seizure": "Seizure",
    "unconscious_person": "Unconscious Person",
    "serious_bleeding": "Serious Bleeding",
    "burns": "Burns",
    "allergic_reaction": "Allergic Reaction",
    "drug_overdose": "Drug Overdose",
    "childbirth": "Childbirth",
    "mental_health_crisis": "Mental Health Crisis",
    "structure_fire": "Structure Fire",
    "vehicle_fire": "Vehicle Fire",
    "wildfire": "Wildfire",
    "electrical_fire": "Electrical Fire",
    "gas_leak": "Gas Leak",
    "smoke_investigation": "Smoke Investigation",
    "explosion": "Explosion",
    "robbery": "Robbery",
    "assault": "Assault",
    "suspicious_activity": "Suspicious Activity",
    "burglary": "Burglary",
    "gunshots_heard": "Gunshots Heard",
    "weapons_complaint": "Weapons Complaint",
    "missing_person": "Missing Person",
    "vandalism": "Vandalism",
    "fight": "Fight",
    "drug_activity": "Drug Activity",
    "public_disturbance": "Public Disturbance",
    "motor_vehicle_accident": "Motor Vehicle Accident",
    "hit_and_run": "Hit and Run",
    "pedestrian_struck": "Pedestrian Struck",
    "road_blocked": "Road Blocked",
    "vehicle_stalled": "Vehicle Stalled",
    "highway_pileup": "Highway Pileup",
    "flooding": "Flooding",
    "earthquake": "Earthquake",
    "tornado": "Tornado",
    "hurricane": "Hurricane",
    "landslide": "Landslide",
    "lightning_strike": "Lightning Strike",
    "building_collapse": "Building Collapse",
    "power_outage": "Power Outage",
    "chemical_spill": "Chemical Spill",
    "gas_leak_or_smell": "Gas Leak or Smell",
    "biohazard_exposure": "Biohazard Exposure",
    "radiation_leak": "Radiation Leak",
    "unknown_substance": "Unknown Substance",
    "environmental_hazard": "Environmental Hazard",
    "suicidal_person": "Suicidal Person",
    "hostage_situation": "Hostage Situation",
    "active_shooter": "Active Shooter",
    "bomb_threat": "Bomb Threat",
    "kidnapping": "Kidnapping",
    "animal_attack": "Animal Attack",
    "emergency_assistance": "Emergency Assistance",
    "alarm_activation": "Alarm Activation",   
    "data_breach": "Data Breach", 
    "system_hack": "System Hack",
    "phishing_attack": "Phishing Attack", 
    "ransomware": "Ransomware",
    "gas_line_rupture": "Gas Line Rupture", 
    "water_main_break": "Water Main Break", 
    "power_grid_failure": "Power Grid Failure",
    "heavy_snowfall": "Heavy Snowfall",
    "blizzard": "Blizzard",
    "heatwave": "Heatwave",
    "storm_surge": "Storm Surge",
    "boat_capsize": "Boat Capsize",
    "drowning": "Drowning",
    "oil_spill": "Oil Spill",
    "water_rescue": "Water Rescue",
    "airplane_crash": "Airplane Crash",
    "emergency_landing": "Emergency Landing",
    "mid_air_distress": "Mid-Air Distress",
    "disease_outbreak": "Disease Outbreak",
    "food_contamination": "Food Contamination",
    "mass_poisoning": "Mass Poisoning",
    "riot": "Riot",
    "stampede": "Stampede",
    "mass_protest": "Mass Protest",
    "overcrowded_event": "Overcrowded Event",
    "bridge_collapse": "Bridge Collapse",
    "tunnel_cave_in": "Tunnel Cave-In",
    "building_integrity_risk": "Building Integrity Risk"
}
